// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF8YF3ArIldUONly47BFVhUNPpG6T6nos',
    appId: '1:247251705078:web:c0878ce4d762c1e3e360d7',
    messagingSenderId: '247251705078',
    projectId: 'gradproject-68531',
    authDomain: 'gradproject-68531.firebaseapp.com',
    storageBucket: 'gradproject-68531.appspot.com',
    measurementId: 'G-FZ2YR62F8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsgmQj6J4U80DRZHMao13B-C6dxszwn7c',
    appId: '1:247251705078:android:b811e4fa904ed3a3e360d7',
    messagingSenderId: '247251705078',
    projectId: 'gradproject-68531',
    storageBucket: 'gradproject-68531.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9jg4oARIysUXEPkFPu3K42dMpARZUFUg',
    appId: '1:247251705078:ios:205bde9721761234e360d7',
    messagingSenderId: '247251705078',
    projectId: 'gradproject-68531',
    storageBucket: 'gradproject-68531.appspot.com',
    iosClientId: '247251705078-bfv0nsg1a1j14mht34h7c4uth8qt8shq.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9jg4oARIysUXEPkFPu3K42dMpARZUFUg',
    appId: '1:247251705078:ios:205bde9721761234e360d7',
    messagingSenderId: '247251705078',
    projectId: 'gradproject-68531',
    storageBucket: 'gradproject-68531.appspot.com',
    iosClientId: '247251705078-bfv0nsg1a1j14mht34h7c4uth8qt8shq.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProject',
  );
}
